controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_homepage:
    path: /
    controller: App\Controller\PizzasController::index

pizzas_ingredients:
    path: /pizzas/ingredients/{id}
    controller: App\Controller\PizzasController::getPizzasIngredients
    methods: GET
    requirements:
        id: \d+